//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Candidate
    {
        public Candidate()
        {
            this.CandidateSkills = new HashSet<CandidateSkill>();
            this.InterviewResults = new HashSet<InterviewResult>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string WorkingPlace { get; set; }
        public string Experience { get; set; }
        public string Certificate { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string LinkCV { get; set; }
        public string English { get; set; }

        public virtual ICollection<CandidateSkill> CandidateSkills { get; set; }
        public virtual ICollection<InterviewResult> InterviewResults { get; set; }
    }
}
