//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Models
{
    using System;
    using System.Collections.Generic;

    public partial class InterviewResult
    {
        public int Id { get; set; }
        public int CandidateId { get; set; }
        public int RequestId { get; set; }
        public Nullable<short> Status { get; set; }
        public Nullable<System.DateTime> InterviewTime { get; set; }
        public string Interviewer { get; set; }
        public int PositionId { get; set; }
        public string Description { get; set; }
        public string Comment { get; set; }
        public Nullable<short> Result { get; set; }
        public string Suggestion { get; set; }

        public virtual Candidate Candidate { get; set; }
        public virtual Position Position { get; set; }
        public virtual Request Request { get; set; }
    }
}
