//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Request
    {
        public Request()
        {
            this.InterviewResults = new HashSet<InterviewResult>();
        }

        public int Id { get; set; }
        public string RequestName { get; set; }
        public string Description { get; set; }

        public virtual ICollection<InterviewResult> InterviewResults { get; set; }
    }
}
